name: Build and upload bottles

on:
  pull_request:
    paths:
      - 'Formula/*.rb'
      - '.github/workflows/*.yml'

jobs:
  build-bottle:
    name: Build a bottle
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    env:
      HOMEBREW_CACHE: /home/linuxbrew/.cache/Homebrew
      HOMEBREW_TEMP: /tmp
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
      HOMEBREW_VERBOSE: 1
    steps:
      - name: Checkout tap
        uses: actions/checkout@v1

      - name: Update-reset Homebrew
        run: brew update-reset

      - name: Setup tap
        run: |
          mkdir -p $(dirname $(brew --repo linuxbrew/xorg))
          ln -s "$PWD" /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg

      - name: Install patchelf
        run: brew install patchelf

      - name: Fix audit errors
        working-directory: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/linuxbrew/homebrew-xorg
        shell: bash
        run: |
          brew audit --fix --except-cops='FormulaAuditStrict/Test' Formula/*.rb
          if [[ -n $(git diff --name-only) ]]
          then
              git add -u
              git commit -m "Fix Homebrew coding style violations (${{github.event.pull_request.number}})"
          fi

      - name: Main test (test-bot)
        run: |
          mkdir /bottles
          cd /bottles
          brew test-bot --tap=linuxbrew/xorg --bintray-org=linuxbrew --skip-recursive-dependents
          mv /bottles $GITHUB_WORKSPACE
        continue-on-error: true

      - name: Update-reset Homebrew (again)
        run: brew update-reset

      - name: Upload bottles to Bintray
        shell: bash
        run: |
          if stat --printf='' *x86_64_linux.bottle*tar.gz 2>/dev/null
          then
              brew test-bot --bintray-org=linuxbrew --ci-upload
          else
              echo "No bottles found!"
          fi
        env:
          HOMEBREW_BINTRAY_USER: ${{secrets.BINTRAY_USER}}
          HOMEBREW_BINTRAY_KEY: ${{secrets.BINTRAY_KEY}}
